### ISSUE TITLE
Add GPS location

### ISSUE THREAD

**Issue by jtiala** [jtiala/lunchwatch-client#2]
Allow users to use their location instead of writing down address

**Comment by billy-le** [comment]
Hello. Can I take this one? I would like to get some experience with PWA's.

**Comment by jtiala** [comment]
@billy-le Hi! Sure! For the UI I was thinking something like a [end adornment](https://material-ui.com/components/text-fields/#input-adornments) for the location text field using the [GpsFixed icon](https://material-ui.com/components/material-icons/).

Thanks for the help and happy hacktoberfest!

**Comment by jtiala** [comment]
Thank you, great work!

Closed in #19
